# Generated by Django 5.0 on 2023-12-26 13:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('original_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mkv', 'mov', '3gp', 'mpg', 'flv', 'ts', 'wmv', 'webm', 'gif', 'jpg', 'heic'])])),
                ('converted_file', models.FileField(blank=True, null=True, upload_to='converted/')),
                ('target_format', models.CharField(max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='converter_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
