# Generated by Django 5.0 on 2024-01-03 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConvertedFile',
            fields=[
                ('id', models.CharField(max_length=111, primary_key=True, serialize=False)),
                ('original_file', models.FileField(upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'heic', 'jpeg', 'pdf', 'png'])])),
                ('converted_file', models.FileField(upload_to='converted/')),
                ('target_format', models.CharField(choices=[('jpg', 'JPG'), ('heic', 'HEIC'), ('pdf', 'PDF'), ('png', 'PNG'), ('jpeg', 'JPEG')], max_length=50)),
            ],
        ),
    ]
