# Generated by Django 5.0 on 2023-12-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='convertedfile',
            name='converted_file',
            field=models.FileField(upload_to='converted/'),
        ),
        migrations.AlterField(
            model_name='convertedfile',
            name='id',
            field=models.CharField(max_length=111, primary_key=True, serialize=False),
        ),
    ]
